// Transactions Actions
export const TRANSACTION_ADD         = 'TRANSACTION_ADD';
export const TRANSACTION_GENERATE    = 'TRANSACTION_GENERATE';
export const TRANSACTION_REMOVE      = 'TRANSACTION_REMOVE';
export const TRANSACTION_REMOVE_ALL  = 'TRANSACTION_CLEAR';
export const TRANSACTION_CLEAR       = 'TRANSACTION_CLEAR';
export const TRANSACTION_FORM_TOGGLE = 'TRANSACTION_FORM_TOGGLE';
export const TRANSACTION_MARK_CLEAR  = 'TRANSACTION_MARK_CLEAR';

// Notifications
export const NOTI_ADD    = 'NOTI_ADD';
export const NOTI_REMOVE = 'NOTI_REMOVE';
