// Transactions Actions
export const TRANSACTION_ADD      = 'TRANSACTION_ADD';
export const TRANSACTION_GENERATE = 'TRANSACTION_GENERATE';
export const TRANSACTION_REMOVE   = 'TRANSACTION_REMOVE';
export const TRANSACTION_UPDATE   = 'TRANSACTION_UPDATE';
